In [1]:
import numpy as np
import time
import scipy.stats as stats
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.linear_model import LinearRegression
from scipy import stats
from sklearn.metrics import log_loss
from sklearn.calibration import CalibratedClassifierCV, calibration_curve
import matplotlib.pyplot as plt
from sklearn.metrics import (brier_score_loss, precision_score, recall_score,
                             f1_score)
from sklearn.metrics import roc_auc_score
import pickle

In [8]:
len(data.columns)

52

In [70]:
def model_RF_test(model_RF, dataX, dataY):
    print("Model performance")
    predict_data = model_RF.predict_proba(dataX)

    # Some stats
    print("Feature Importance : ")
    print(model_RF.best_estimator_.feature_importances_)
    print("Total number of WNV occurrence in test set : " + str(len(dataY[dataY > 0])))
    
    print("Number of WNV occurrence the model is able to capture in test set:" + str(
        dataY[np.where(predict_data[:, 1] > 0)].sum()))
    print('Expected number of WNV occurence' + str(predict_data[:,1].mean() * len(dataY)))
    print('True number of WNV occurence' + str(dataY.sum()))
    print('model best parameters')
    print(model_RF.get_params)
    print("Log loss : " + str(log_loss(dataY, predict_data)))

    print("AUC: " + str(roc_auc_score(dataY, predict_data[:,1])))

    print(
        "This is to test the performance of random forest model, ideally, the logloss is low and also it is able to "
        "capture most of the WNV occurrence")

    return None  # Check how many wnv it predicts

In [7]:
data = pd.read_sas('/home/guangya/Downloads/wnv_2245new.sas7bdat') 

In [3]:
ip = model_1_max.best_estimator_.feature_importances_

In [38]:
['tempc', 'preci', 'templag1', 'templag2',
       'templag3', 'templag4', 'precilag1', 'precilag2', 'precilag3',
       'precilag4', 'mirmean', 'mirlag1', 'mirlag2', 'mirlag3', 'mirlag4',
       'totpop', 'dlipct', 'dmipct', 'Jantemp', 'hpctpreww', 'hpctpostww',
       'hpct7089']

Index(['hexid', 'Input_FID', 'tempc', 'preci', 'templag1', 'templag2',
       'templag3', 'templag4', 'precilag1', 'precilag2', 'precilag3',
       'precilag4', 'mirmean', 'mirlag1', 'mirlag2', 'mirlag3', 'mirlag4',
       'totpop', 'dlipct', 'dmipct', 'Jantemp', 'hpctpreww', 'hpctpostww',
       'hpct7089'],
      dtype='object')

In [46]:
description = ['unique hexid used by arcgis',
 'unique id',
'weekly mean temperature (C)',
'weekly mean precipitation (mm)',
'year',
'week of the year (Jan 1 = week 1)',
'temperature lag 1 week',
'temperature lag 2 weeks',
'temperature lag 3 weeks',
'temperature lag 4 weeks',
'precipitation lag 1 week',
'precipitation lag 2 weeks',
'precipitation lag 3 weeks',
'precipitation lag 4 weeks',
'mean mosquito infection rate',
'mosquito infection rate lag 1 week',
'mosquito infection rate lag 2 weeks',
'mosquito infection rate lag 3 weeks',
'mosquito infection rate lag 4 weeks'
,'total human population',
'% white'
,'% black',
'% asian',
'% hispanic',
'average household income',
'open water percent',
'developed open space percent',
'developed low intensity percent',
'developed medium intensity percent',
'developed high intensity percent',
'barren land percent',
'deciduous forest percent',
'evergreen forest percent',
'mixed forest percent',
'shrub percent',
'grassland percent',
'pasture percent',
'cultivated crops percent',
'woody wetlands percent',
'emergent herbaceous wetlands percent',
'mean temperature in January',
'N/A',
'housing % pre world-war 2',
'housing % post world-war 2 (1945-1969)',
'housing % 1970-1989',
'housing % post 1990',
              'Average household Income(K)']

In [31]:
features = data.columns.drop(['yrweeks', 'yrwksfid', 'yr_hexid', 'year', 'wnvbinary'])

In [49]:
s = np.array([features,description,ip]).T

In [50]:
s.shape

(47, 3)

In [51]:
temp = pd.DataFrame(s,columns=['feature_name','description','feature_importance'])

In [52]:
temp

feature_name                             description feature_importance
0         hexid             unique hexid used by arcgis          0.0262945
1     Input_FID                               unique id          0.0257839
2         tempc             weekly mean temperature (C)          0.0345134
3         preci          weekly mean precipitation (mm)          0.0310655
4            yr                                    year         0.00981822
5         weeks       week of the year (Jan 1 = week 1)         0.00860826
6      templag1                  temperature lag 1 week          0.0366341
7      templag2                 temperature lag 2 weeks          0.0358726
8      templag3                 temperature lag 3 weeks          0.0363154
9      templag4                 temperature lag 4 weeks          0.0367589
10    precilag1                precipitation lag 1 week          0.0306447
11    precilag2               precipitation lag 2 weeks          0.0311156
12    precilag3               precipitation lag 3 weeks          0.0320155
13    precilag4               precipitation lag 4 weeks          0.0316537
14      mirmean            mean mosquito infection rate           0.034072
15      mirlag1      mosquito infection rate lag 1 week          0.0359839
16      mirlag2     mosquito infection rate lag 2 weeks          0.0358548
17      mirlag3     mosquito infection rate lag 3 weeks          0.0336327
18      mirlag4     mosquito infection rate lag 4 weeks           0.033744
19       totpop                  total human population          0.0289874
20     whitepct                                 % white          0.0245016
21     blackpct                                 % black          0.0236782
22     asianpct                                 % asian          0.0239008
23  hispanicpct                              % hispanic          0.0218244
24       Income                average household income          0.0246348
25        owpct                      open water percent         0.00266412
26       dospct            developed open space percent            0.02064
27       dlipct         developed low intensity percent           0.026513
28       dmipct      developed medium intensity percent           0.025883
29       dhipct        developed high intensity percent          0.0213744
30        blpct                     barren land percent        0.000386777
31        dfpct                deciduous forest percent          0.0033449
32        efpct                evergreen forest percent        0.000604118
33        mfpct                    mixed forest percent         0.00165944
34     shrubpct                           shrub percent         0.00048802
35     glandpct                       grassland percent          0.0017847
36   pasturepct                         pasture percent         0.00112839
37        ccpct                cultivated crops percent         0.00137582
38        wwpct                  woody wetlands percent         0.00300273
39       ehwpct    emergent herbaceous wetlands percent        0.000330284
40      Jantemp             mean temperature in January          0.0337713
41     PopYesNo                                     N/A                  0
42    hpctpreww               housing % pre world-war 2          0.0256384
43   hpctpostww  housing % post world-war 2 (1945-1969)           0.025436
44     hpct7089                     housing % 1970-1989          0.0267511
45   hpctpost90                     housing % post 1990          0.0242146
46      income1             Average household Income(K)          0.0251003

In [53]:
temp.to_csv('temp.csv')

In [31]:
np.where(ip > (ip.mean() + 0.3 * ip.std()))

(array([ 0,  1,  2,  3,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 27, 28, 40, 42, 43, 44]),)

In [28]:
ip[ip > ip.mean() + 0.3 * ip.std()]

array([0.02629452, 0.02578387, 0.03451336, 0.03106555, 0.0366341 ,
       0.03587256, 0.03631539, 0.03675893, 0.03064472, 0.03111556,
       0.03201555, 0.0316537 , 0.03407201, 0.03598392, 0.03585484,
       0.03363267, 0.03374397, 0.02898736, 0.02651296, 0.02588299,
       0.03377126, 0.02563835, 0.02543598, 0.0267511 ])

In [51]:
len(data.columns.drop(['wnvbinary', 'yrweeks', 'yrwksfid', 'yr_hexid', 'year'])[np.where(ip > (ip.mean() + 0.3 * ip.std()))[0]])

24

In [16]:
model_1_second = pickle.load(open('/home/guangya/Downloads/RF_model_CV_final_11-27', 'rb'))

In [13]:
ip = model_1_second.best_estimator_.feature_importances_

NameError: name 'model_1_second' is not defined

In [19]:
model_1_second.best_score_

-0.006766511383922191

In [17]:
model_1_second.best_score_ # This one is not correct compared to the procedure

-0.006766511383922191

In [40]:
model_2_max = pickle.load(open('/home/guangya/Downloads/RF_model_CV_final_1_22_2020', 'rb'))

In [41]:
len(model_2_max.best_estimator_.feature_importances_)

44

In [45]:
data.drop(columns=['yrweeks', 'yrwksfid', 'yr_hexid', 'year', 'income1','hexid','PopYesNo']).columns

Index(['Input_FID', 'tempc', 'preci', 'yr', 'weeks', 'templag1', 'templag2',
       'templag3', 'templag4', 'precilag1', 'precilag2', 'precilag3',
       'precilag4', 'wnvbinary', 'mirmean', 'mirlag1', 'mirlag2', 'mirlag3',
       'mirlag4', 'totpop', 'whitepct', 'blackpct', 'asianpct', 'hispanicpct',
       'Income', 'owpct', 'dospct', 'dlipct', 'dmipct', 'dhipct', 'blpct',
       'dfpct', 'efpct', 'mfpct', 'shrubpct', 'glandpct', 'pasturepct',
       'ccpct', 'wwpct', 'ehwpct', 'Jantemp', 'hpctpreww', 'hpctpostww',
       'hpct7089', 'hpctpost90'],
      dtype='object')

In [46]:
model_2_max.best_estimator_.feature_importances_

array([3.07241599e-02, 3.52793670e-02, 2.94239579e-02, 5.00553478e-03,
       2.82801749e-03, 3.51095252e-02, 3.29032586e-02, 3.83755095e-02,
       5.08218018e-02, 2.94324019e-02, 3.75500606e-02, 3.57218602e-02,
       2.96077186e-02, 4.07439804e-02, 3.56989002e-02, 3.20231265e-02,
       3.27193058e-02, 3.40802896e-02, 3.60028692e-02, 2.69190838e-02,
       2.33178343e-02, 2.38853294e-02, 2.18819014e-02, 3.08823448e-02,
       9.42384096e-04, 1.91792734e-02, 4.45308560e-02, 2.61562798e-02,
       2.46767768e-02, 6.44415056e-04, 1.94232453e-03, 0.00000000e+00,
       1.50658312e-03, 9.04898781e-04, 5.25417520e-04, 9.23886820e-06,
       7.60867399e-04, 1.64773354e-03, 0.00000000e+00, 3.39752008e-02,
       3.16871500e-02, 2.84675276e-02, 2.53574278e-02, 2.61475059e-02])

In [39]:
model_2_max.best_estimator_.feature_importances_

array([3.07241599e-02, 3.52793670e-02, 2.94239579e-02, 5.00553478e-03,
       2.82801749e-03, 3.51095252e-02, 3.29032586e-02, 3.83755095e-02,
       5.08218018e-02, 2.94324019e-02, 3.75500606e-02, 3.57218602e-02,
       2.96077186e-02, 4.07439804e-02, 3.56989002e-02, 3.20231265e-02,
       3.27193058e-02, 3.40802896e-02, 3.60028692e-02, 2.69190838e-02,
       2.33178343e-02, 2.38853294e-02, 2.18819014e-02, 3.08823448e-02,
       9.42384096e-04, 1.91792734e-02, 4.45308560e-02, 2.61562798e-02,
       2.46767768e-02, 6.44415056e-04, 1.94232453e-03, 0.00000000e+00,
       1.50658312e-03, 9.04898781e-04, 5.25417520e-04, 9.23886820e-06,
       7.60867399e-04, 1.64773354e-03, 0.00000000e+00, 3.39752008e-02,
       3.16871500e-02, 2.84675276e-02, 2.53574278e-02, 2.61475059e-02])

In [47]:
model_2_second  = pickle.load(open('/home/guangya/Downloads/RF_model_CV_final_1_30_2020', 'rb'))

In [58]:
columns = ['tempc', 'preci', 'templag1', 'templag2', 'templag3', 'templag4',
       'precilag1', 'precilag2', 'precilag3', 'precilag4', 'mirmean',
       'mirlag1', 'mirlag2', 'mirlag3', 'mirlag4', 'totpop', 'whitepct',
       'blackpct', 'asianpct', 'Income', 'dlipct', 'dmipct', 'dhipct',
       'Jantemp', 'hpctpreww', 'hpctpostww', 'hpct7089', 'hpctpost90']

In [56]:
ip_22 = model_2_second.best_estimator_.feature_importances_

In [68]:
np.array(columns)[np.where(ip_22 > (ip_22.mean() + 0.3 * ip_22.std()))[0]]

array(['templag3', 'templag4', 'precilag2', 'mirmean', 'mirlag1',
       'totpop', 'dlipct'], dtype='<U10')

In [67]:
np.array(columns)[[1,3]]

array(['preci', 'templag2'], dtype='<U10')

In [55]:
model_2_cum = pickle.load(open('/home/guangya/Downloads/RF_agg_model_CV_final_1_22_2020', 'rb'))

In [35]:
model_2_cum.best_score_

-0.012665445530163447

In [3]:
x_selected = data[data.drop(columns=['wnvbinary','yrweeks','yrwksfid','yr_hexid','year']).columns[[7,8,9,10,15,16,17,20]]].values
y = data['wnvbinary'].values 
y_selected = y

In [4]:
def model_RF_test(model_RF, dataX, dataY):
    print("Model performance")
    predict_data = model_RF.predict_proba(dataX)
    
    # Some stats
    print("Feature Importantce : ")
    print(model_RF.feature_importances_)
    print("Total number of WNV occurence in test set : " + str(len(dataY[dataY > 0])))
    
    print("Number of WNV occurence the model is able to capture in test set:" + str(dataY[np.where(predict_data[:,1]  > 0)].sum()))
    
    print("Expected number of WNV occurence of models aussume prediction is normally distributed : " + str(predict_data[:,1].mean() * len(predict_data)))
    print("Log loss : " + str(log_loss(dataY,predict_data)))
    
    print("This is to test the performance of random forest model, ideally, the logloss is low and also it is able to capture most of the WNV occurence, and also it is neither over predicting" +  
          "nor under predicting")
    print("AUC : " + str( roc_auc_score(dataY,predict_data[:,1])))
    
    return None # Check how many wnv it predicts

In [69]:
import numpy as np
import time
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import log_loss
import pickle
from sklearn.utils import class_weight

"""
This code fits the Random Forest model. Cross validation is preformed in another
script.
"""

time_start = time.time()
# data = pd.read_sas('/home/shared/cprhd/DATA_CPRHD_SES/wnv_2245new.sas7bdat')  # In the Cook_Dupage Directory
print("Data read in:", time.time() - time_start)

x = data.drop(columns=['yrweeks', 'yrwksfid', 'yr_hexid', 'year', 'income1','hexid','PopYesNo'])


columns = ['tempc', 'preci', 'templag1', 'templag2',
       'templag3', 'templag4', 'precilag1', 'precilag2', 'precilag3',
       'precilag4', 'mirmean', 'mirlag1', 'mirlag2', 'mirlag3', 'mirlag4',
       'totpop', 'dlipct', 'dmipct', 'Jantemp', 'hpctpreww', 'hpctpostww',
       'hpct7089']
x_selected = x[columns].values
y_selected = x['wnvbinary'].values

trainX_sel, testX_sel, trainY_sel, testY_sel = train_test_split(x_selected, y_selected, test_size=0.2, random_state=1) # CV
print("data split:", time.time() - time_start)

model_RF_best_2 = RandomForestClassifier(n_estimators=1300,
                                         n_jobs=-1,
                                         max_depth=60,
                                         min_samples_leaf = 15,
                                         bootstrap=True)
                                            
print("Classifier established:", time.time() - time_start)



model_RF_best_2.fit(trainX_sel, trainY_sel)
print("model fit:", time.time() - time_start)

pickle.dump(model_RF_best_2, open('/home/jallen17/CPRHD_SES/RF_model_1_2_fit', 'wb'))
print("Fitting complete. Model saved as RF_model_fit")

Data read in: 9.202957153320312e-05
data split: 3.3865740299224854
Classifier established: 3.3894569873809814


KeyboardInterrupt: 

In [5]:
trainX_sel, testX_sel, trainY_sel, testY_sel = train_test_split(x_selected, y_selected, test_size = 0.2, shuffle = True) # CV