In [2]:
import numpy as np
import time
import scipy.stats as stats
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.linear_model import LinearRegression
from scipy import stats
from sklearn.metrics import log_loss
from sklearn.calibration import CalibratedClassifierCV, calibration_curve
import matplotlib.pyplot as plt
from sklearn.metrics import (brier_score_loss, precision_score, recall_score,
                             f1_score)

# Explore and extra data of particular periods of interest

In [3]:
data = pd.read_sas('/home/guangya/Downloads/wnv_2245new.sas7bdat') #Data from week 22 to 45, which is what i used for latter models

In [3]:
data.head() # Available features in the data set, More description is the final.xlsw file

hexid  Input_FID    tempc      preci      yr  weeks    yrweeks  \
0    1.0      130.0  16.9758   6.046130  2005.0   22.0  b'200522'   
1    1.0      130.0  25.3449  58.968242  2005.0   23.0  b'200523'   
2    1.0      130.0  21.0872  15.114200  2005.0   24.0  b'200524'   
3    1.0      130.0  22.3485   0.000000  2005.0   25.0  b'200525'   
4    1.0      130.0  25.7740   6.371029  2005.0   26.0  b'200526'   

       yrwksfid  templag1  templag2  ...      wwpct  ehwpct   yr_hexid  \
0  b'200522130'   15.9957   13.7796  ...  27.184466     0.0  b'2005,1'   
1  b'200523130'   16.9758   15.9957  ...  27.184466     0.0  b'2005,1'   
2  b'200524130'   25.3449   16.9758  ...  27.184466     0.0  b'2005,1'   
3  b'200525130'   21.0872   25.3449  ...  27.184466     0.0  b'2005,1'   
4  b'200526130'   22.3485   21.0872  ...  27.184466     0.0  b'2005,1'   

    Jantemp  PopYesNo  hpctpreww  hpctpostww  hpct7089 hpctpost90    income1  
0 -3.815482       1.0        0.0         0.0       0.0        0.0  41.979816  
1 -3.815482       1.0        0.0         0.0       0.0        0.0  41.979816  
2 -3.815482       1.0        0.0         0.0       0.0        0.0  41.979816  
3 -3.815482       1.0        0.0         0.0       0.0        0.0  41.979816  
4 -3.815482       1.0        0.0         0.0       0.0        0.0  41.979816  

[5 rows x 52 columns]

In [4]:
data.isna().sum() # Check na

hexid               0
Input_FID           0
tempc               0
preci               0
yr                  0
weeks               0
yrweeks             0
yrwksfid            0
templag1            0
templag2            0
templag3            0
templag4            0
precilag1           0
precilag2           0
precilag3           0
precilag4           0
wnvbinary           0
mirmean             0
year           150510
mirlag1             0
mirlag2             0
mirlag3             0
mirlag4             0
totpop              0
whitepct            0
blackpct            0
asianpct            0
hispanicpct         0
Income              0
owpct               0
dospct              0
dlipct              0
dmipct              0
dhipct              0
blpct               0
dfpct               0
efpct               0
mfpct               0
shrubpct            0
glandpct            0
pasturepct          0
ccpct               0
wwpct               0
ehwpct              0
yr_hexid            0
Jantemp   

In [5]:
data.drop(columns=['wnvbinary','yrweeks','yrwksfid','yr_hexid','year']).isna().sum() # Drop year column so that so na appear

hexid          0
Input_FID      0
tempc          0
preci          0
yr             0
weeks          0
templag1       0
templag2       0
templag3       0
templag4       0
precilag1      0
precilag2      0
precilag3      0
precilag4      0
mirmean        0
mirlag1        0
mirlag2        0
mirlag3        0
mirlag4        0
totpop         0
whitepct       0
blackpct       0
asianpct       0
hispanicpct    0
Income         0
owpct          0
dospct         0
dlipct         0
dmipct         0
dhipct         0
blpct          0
dfpct          0
efpct          0
mfpct          0
shrubpct       0
glandpct       0
pasturepct     0
ccpct          0
wwpct          0
ehwpct         0
Jantemp        0
PopYesNo       0
hpctpreww      0
hpctpostww     0
hpct7089       0
hpctpost90     0
income1        0
dtype: int64

In [5]:
from sklearn.utils import class_weight

In [7]:
np.unique(y)

array([0., 1.])

In [9]:
y

array([0., 0., 0., ..., 0., 0., 0.])

In [14]:
class_weights = class_weight.compute_class_weight('balanced' , classes=np.unique(y),y = y)

In [4]:
x = data.drop(columns=['wnvbinary','yrweeks','yrwksfid','yr_hexid','year']).values # Drop extra column
y = data['wnvbinary'].values

In [16]:
x = x.astype('float64')

In [ ]:
trainX, testX, trainY, testY = train_test_split(x, y, test_size = 0.2, shuffle = True) # CV

In [8]:
# some spot check for data
data[data['hexid'] == 1431]['blackpct'].unique()

array([4.28479215])

In [9]:
data[data['hexid'] == 1831]['whitepct'].unique()

array([86.10261915])

In [10]:
data[data['hexid'] == 1831]['dmipct'].unique() 

array([14.42441054])

In [11]:
data[data['hexid'] == 3121]['income1'].unique() # The Geological and social data is likely a 10 year estimate here, which does not change from 2005-2016

array([100.88401563])

In [12]:
x = data[['yr','templag2','templag3','templag4','precilag2','mirlag1','mirlag2','mirlag3','mirlag4', 'whitepct','owpct','dmipct','dhipct']].values
# Data set for the best model described in paper, table5.
# However, random forest use a different feature selection algorithm 
# so that this might not be the optimal one for oue models. Since it's much slower to train all, I will use ALL features for further optimization later
y = data['wnvbinary'].values 
x = x.astype('float64')

In [14]:
trainX_total, testX_total, trainY_total, testY_total = train_test_split(x_total, y_total, test_size = 0.2, shuffle = True) # CV for all

NameError: name 'x_total' is not defined

# Test on Random Forest

In [ ]:
def model_RF_test(model_RF, dataX, dataY):
    print("Model performance")
    predict_data = model_RF.predict_proba(dataX)
    
    # Some stats
    print("Feature Importantce : ")
    print(model_RF.feature_importances_)
    print("Total number of WNV occurence in test set : " + str(len(dataY[dataY > 0])))
    
    print("Number of WNV occurence the model is able to capture in test set:" + str(dataY[np.where(predict_data[:,1]  > 0)].sum()))
    
    print("Expected number of WNV occurence of models aussume prediction is normally distributed : " + str(predict_data[:,1].mean() * len(predict_data)))
    print("Log loss : " + str(log_loss(dataY,predict_data)))
    
    print("This is to test the performance of random forest model, ideally, the logloss is low and also it is able to capture most of the WNV occurence, and also it is neither over predicting" +  
          "nor under predicting")
    
    return None # Check how many wnv it predicts

In [17]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=0)
X_resampled, y_resampled = rus.fit_resample(trainX_total, trainY_total)
time_start = time.time()
model_RF1 = RandomForestClassifier(n_estimators=400,
                                 n_jobs = -1,
                                 max_features=None,
                                 max_depth= None,
                                 bootstrap=True,
                                class_weight='balanced'
                                 ) # Use undersampling to see if it worked
model_RF1.fit(X_resampled, y_resampled)
print("time consumed:", time.time() - time_start) 

Using TensorFlow backend.


time consumed: 3.264770030975342


In [60]:
model_RF_test(model_RF1,testX_total,testY_total) # The result tend to predict a lot of 1s, which is very biased.

Model performance
Feature Importantce : 
[0.00999531 0.01067965 0.01496773 0.01082702 0.0054172  0.02645585
 0.02794946 0.02833401 0.03969041 0.03359853 0.01333262 0.01407395
 0.01410982 0.01532784 0.02686748 0.13324849 0.11390923 0.11554932
 0.01995433 0.13395407 0.00646951 0.00946079 0.00790575 0.00963136
 0.00768387 0.00252334 0.01573296 0.01404953 0.01017898 0.01184233
 0.00080315 0.0024459  0.0021979  0.00341815 0.00042789 0.00192679
 0.00188718 0.00171914 0.00172571 0.00063831 0.02298358 0.
 0.01426518 0.01014777 0.01229566 0.01120487 0.00819208]
Total number of WNV occurence in test set : 173
Number of WNV occurence the model is able to capture in test set:173.0
Expected number of WNV occurence of models aussume prediction is normally distributed : 69593.33
Log loss : 0.4248442677492819
This is to test the performance of random forest model, ideally, the logloss is low and also it is able to capture most of the WNV occurence, and also it is neither over predictingnor under predi

In [20]:
np.argsort()

SyntaxError: invalid syntax (<ipython-input-20-be2c916f2ef5>, line 1)

In [37]:
data

hexid  Input_FID      tempc      preci      yr  weeks   templag1  \
0           1.0      130.0  16.975800   6.046130  2005.0   22.0  15.995700   
1           1.0      130.0  25.344900  58.968242  2005.0   23.0  16.975800   
2           1.0      130.0  21.087200  15.114200  2005.0   24.0  25.344900   
3           1.0      130.0  22.348500   0.000000  2005.0   25.0  21.087200   
4           1.0      130.0  25.774000   6.371029  2005.0   26.0  22.348500   
5           1.0      130.0  22.277000   3.417303  2005.0   27.0  25.774000   
6           1.0      130.0  24.915200  10.102133  2005.0   28.0  22.277000   
7           1.0      130.0  25.904900  18.433824  2005.0   29.0  24.915200   
8           1.0      130.0  23.836800  45.339948  2005.0   30.0  25.904900   
9           1.0      130.0  24.750600   5.782040  2005.0   31.0  23.836800   
10          1.0      130.0  24.486600  29.893326  2005.0   32.0  24.750600   
11          1.0      130.0  22.530800  82.774868  2005.0   33.0  24.486600   
12          1.0      130.0  20.684000   0.000000  2005.0   34.0  22.530800   
13          1.0      130.0  21.462500   0.000000  2005.0   35.0  20.684000   
14          1.0      130.0  22.205100   0.000000  2005.0   36.0  21.462500   
15          1.0      130.0  21.505600  28.590125  2005.0   37.0  22.205100   
16          1.0      130.0  20.865600   4.008865  2005.0   38.0  21.505600   
17          1.0      130.0  15.853300  22.921730  2005.0   39.0  20.865600   
18          1.0      130.0  18.609400   9.878610  2005.0   40.0  15.853300   
19          1.0      130.0  12.891200   1.922530  2005.0   41.0  18.609400   
20          1.0      130.0  11.802600   0.985842  2005.0   42.0  12.891200   
21          1.0      130.0   6.428700  58.891882  2005.0   43.0  11.802600   
22          1.0      130.0  11.154600  14.621900  2005.0   44.0   6.428700   
23          1.0      130.0   9.379400  32.668568  2005.0   45.0  11.154600   
24          1.0      130.0  19.035700  25.478804  2006.0   22.0  22.777500   
25          1.0      130.0  18.743600  48.270000  2006.0   23.0  19.035700   
26          1.0      130.0  22.865400   6.582330  2006.0   24.0  18.743600   
27          1.0      130.0  20.032300   4.509644  2006.0   25.0  22.865400   
28          1.0      130.0  22.174000   6.395008  2006.0   26.0  20.032300   
29          1.0      130.0  22.174000  16.473980  2006.0   27.0  22.174000   
...         ...        ...        ...        ...     ...    ...        ...   
1444866  5345.0     7938.0  13.738173   5.133420  2015.0   40.0  15.778857   
1444867  5345.0     7938.0  12.306907   0.000000  2015.0   41.0  13.738173   
1444868  5345.0     7938.0  12.671263  17.259050  2015.0   42.0  12.306907   
1444869  5345.0     7938.0   8.936820  21.118070  2015.0   43.0  12.671263   
1444870  5345.0     7938.0  12.382840  18.504350  2015.0   44.0   8.936820   
1444871  5345.0     7938.0   5.583054  11.644016  2015.0   45.0  12.382840   
1444872  5345.0     7938.0  21.340400  26.582100  2016.0   22.0  21.081771   
1444873  5345.0     7938.0  18.935614  37.295534  2016.0   23.0  21.340400   
1444874  5345.0     7938.0  21.785443  19.030300  2016.0   24.0  18.935614   
1444875  5345.0     7938.0  22.949214  34.852578  2016.0   25.0  21.785443   
1444876  5345.0     7938.0  21.451786   1.649019  2016.0   26.0  22.949214   
1444877  5345.0     7938.0  22.498986  23.186886  2016.0   27.0  21.451786   
1444878  5345.0     7938.0  23.500657   1.570530  2016.0   28.0  22.498986   
1444879  5345.0     7938.0  25.015086  26.703980  2016.0   29.0  23.500657   
1444880  5345.0     7938.0  25.310386  87.801292  2016.0   30.0  25.015086   
1444881  5345.0     7938.0  24.098871   3.147120  2016.0   31.0  25.310386   
1444882  5345.0     7938.0  24.935200   4.108010  2016.0   32.0  24.098871   
1444883  5345.0     7938.0  24.515114  34.203858  2016.0   33.0  24.935200   
1444884  5345.0     7938.0  21.641071  33.420900  2016.0   34.0  24.515114   
1444885  5345.0     7938.0  21.8

In [3]:
data = data.drop(columns=['wnvbinary','yrweeks','yrwksfid','yr_hexid','year'])

In [16]:
data[['Income','income1']]

Income     income1
0         41979.816406   41.979816
1         41979.816406   41.979816
2         41979.816406   41.979816
3         41979.816406   41.979816
4         41979.816406   41.979816
5         41979.816406   41.979816
6         41979.816406   41.979816
7         41979.816406   41.979816
8         41979.816406   41.979816
9         41979.816406   41.979816
10        41979.816406   41.979816
11        41979.816406   41.979816
12        41979.816406   41.979816
13        41979.816406   41.979816
14        41979.816406   41.979816
15        41979.816406   41.979816
16        41979.816406   41.979816
17        41979.816406   41.979816
18        41979.816406   41.979816
19        41979.816406   41.979816
20        41979.816406   41.979816
21        41979.816406   41.979816
22        41979.816406   41.979816
23        41979.816406   41.979816
24        41979.816406   41.979816
25        41979.816406   41.979816
26        41979.816406   41.979816
27        41979.816406   41.979816
28        41979.816406   41.979816
29        41979.816406   41.979816
...                ...         ...
1444866  105106.953125  105.106953
1444867  105106.953125  105.106953
1444868  105106.953125  105.106953
1444869  105106.953125  105.106953
1444870  105106.953125  105.106953
1444871  105106.953125  105.106953
1444872  105106.953125  105.106953
1444873  105106.953125  105.106953
1444874  105106.953125  105.106953
1444875  105106.953125  105.106953
1444876  105106.953125  105.106953
1444877  105106.953125  105.106953
1444878  105106.953125  105.106953
1444879  105106.953125  105.106953
1444880  105106.953125  105.106953
1444881  105106.953125  105.106953
1444882  105106.953125  105.106953
1444883  105106.953125  105.106953
1444884  105106.953125  105.106953
1444885  105106.953125  105.106953
1444886  105106.953125  105.106953
1444887  105106.953125  105.106953
1444888  105106.953125  105.106953
1444889  105106.953125  105.106953
1444890  105106.953125  105.106953
1444891  105106.953125  105.106953
1444892  105106.953125  105.106953
1444893  105106.953125  105.106953
1444894  105106.953125  105.106953
1444895  105106.953125  105.106953

[1444896 rows x 2 columns]

In [5]:
1/47 # Mean importantce

0.02127659574468085

In [33]:
data.columns[[2,3,6,7,8,9,10,11,12,13,14,15,16,17,-7]] # If set cutoffs as 0.03, these are the dominant features for the model

Index(['tempc', 'preci', 'templag1', 'templag2', 'templag3', 'templag4',
       'precilag1', 'precilag2', 'precilag3', 'precilag4', 'mirmean',
       'mirlag1', 'mirlag2', 'mirlag3', 'Jantemp'],
      dtype='object')

In [12]:
data.columns[[4,5,25,26,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-6]] # unimportant Features that has importance less than 0.021, which is the mean importantce

Index(['yr', 'weeks', 'owpct', 'dospct', 'blpct', 'dfpct', 'efpct', 'mfpct',
       'shrubpct', 'glandpct', 'pasturepct', 'ccpct', 'wwpct', 'ehwpct',
       'PopYesNo'],
      dtype='object')

In [13]:
data.drop(columns=data.columns[[4,5,25,26,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-6]])# relatively important Features that has importance grater than 0.021

Index(['hexid', 'Input_FID', 'tempc', 'preci', 'templag1', 'templag2',
       'templag3', 'templag4', 'precilag1', 'precilag2', 'precilag3',
       'precilag4', 'mirmean', 'mirlag1', 'mirlag2', 'mirlag3', 'mirlag4',
       'totpop', 'whitepct', 'blackpct', 'asianpct', 'hispanicpct', 'Income',
       'dlipct', 'dmipct', 'dhipct', 'Jantemp', 'hpctpreww', 'hpctpostww',
       'hpct7089', 'hpctpost90', 'income1'],
      dtype='object')

In [ ]:
# Temp,precipatation, and mir is indeed most relevant than social economical features, but some social economical features are still useful in some extent.

In [16]:
# Add translation of features. Next step, train two models with smarter parameters and also taking a look at isda model and see if they have some inisght

In [19]:
rus = RandomUnderSampler(random_state=0)
X_resampled, y_resampled = rus.fit_resample(trainX, trainY)
time_start = time.time()
model_RF2 = RandomForestClassifier(n_estimators=400,
                                 n_jobs = -1,
                                 max_features=None,
                                 max_depth= None,
                                 bootstrap=True,
                                class_weight='balanced'
                                 ) # Use undersampling to see if it worked
model_RF2.fit(X_resampled, y_resampled)
print("time consumed:", time.time() - time_start) 

time consumed: 1.166808843612671


In [61]:
model_RF_test(model_RF2,testX,testY) 

Model performance
Feature Importantce : 
[0.02332565 0.07673163 0.09381062 0.08244171 0.04115731 0.09283884
 0.32511096 0.03987311 0.05722872 0.04018178 0.02340537 0.06687365
 0.03702065]
Total number of WNV occurence in test set : 196
Number of WNV occurence the model is able to capture in test set:195.0
Expected number of WNV occurence of models aussume prediction is normally distributed : 73071.56249999999
Log loss : 0.42897848898311103
This is to test the performance of random forest model, ideally, the logloss is low and also it is able to capture most of the WNV occurence, and also it is neither over predictingnor under predicting


In [33]:
time_start = time.time()
model_RF3 = RandomForestClassifier(n_estimators=200,
                                 n_jobs = -1,
                                 max_features='sqrt',
                                 max_depth= 20,
                                 bootstrap=True,
                                   min_samples_leaf= 2,
                                class_weight='balanced'
                                 ) # Try more trees and see if calibration curve gets better
model_RF3.fit(trainX_total, trainY_total)
print("time consumed:", time.time() - time_start) 

time consumed: 307.3307168483734


In [88]:
x = sorted(model_RF3.feature_importances_)[::-1]
seq = [list(model_RF3.feature_importances_).index(v) for v in x]

In [91]:
seq[:10]

[15, 16, 17, 19, 8, 14, 18, 9, 7, 5]

In [57]:
model_RF_test(model_RF3,testX_total,testY_total)

Model performance
Feature Importantce : 
[1.30942271e-02 1.28020934e-02 2.92368487e-02 1.19465584e-02
 7.07868054e-03 4.19247572e-02 2.91652172e-02 4.69769293e-02
 6.08182076e-02 4.90170180e-02 1.13150864e-02 1.15022790e-02
 1.32276167e-02 1.27103614e-02 5.50808196e-02 9.72655123e-02
 7.87749447e-02 7.80864630e-02 5.01764878e-02 7.08532494e-02
 8.85207640e-03 9.74098519e-03 8.80785359e-03 1.12414583e-02
 9.87450040e-03 6.71593176e-03 1.24806795e-02 1.14679958e-02
 1.23319782e-02 1.02753625e-02 1.17618205e-03 8.00185418e-03
 9.13261608e-04 3.29746529e-03 4.22286487e-04 4.30764953e-03
 1.68786058e-03 9.07328043e-04 4.42005112e-03 7.72870641e-05
 2.79016966e-02 0.00000000e+00 1.64946315e-02 9.70867099e-03
 1.27331784e-02 1.49233092e-02 1.01851078e-02]
Total number of WNV occurence in test set : 173
Number of WNV occurence the model is able to capture in test set:165.0
Expected number of WNV occurence of models aussume prediction is normally distributed : 13746.057522374354
Log loss : 0.06

In [102]:
data.drop(columns=['wnvbinary','yrweeks','yrwksfid','yr_hexid','year']).columns

Index(['hexid', 'Input_FID', 'tempc', 'preci', 'yr', 'weeks', 'templag1',
       'templag2', 'templag3', 'templag4', 'precilag1', 'precilag2',
       'precilag3', 'precilag4', 'mirmean', 'mirlag1', 'mirlag2', 'mirlag3',
       'mirlag4', 'totpop', 'whitepct', 'blackpct', 'asianpct', 'hispanicpct',
       'Income', 'owpct', 'dospct', 'dlipct', 'dmipct', 'dhipct', 'blpct',
       'dfpct', 'efpct', 'mfpct', 'shrubpct', 'glandpct', 'pasturepct',
       'ccpct', 'wwpct', 'ehwpct', 'Jantemp', 'PopYesNo', 'hpctpreww',
       'hpctpostww', 'hpct7089', 'hpctpost90', 'income1'],
      dtype='object')

In [35]:
time_start = time.time()
model_RF4 = RandomForestClassifier(n_estimators=200,
                                 n_jobs = -1,
                                 max_features='sqrt',
                                 max_depth= 20,
                                 bootstrap=True,
                                   min_samples_leaf= 2,
                                class_weight='balanced'
                                 ) # Try more trees and see if calibration curve gets better
model_RF4.fit(trainX, trainY)
print("time consumed:", time.time() - time_start) 

time consumed: 218.0876429080963


In [62]:
model_RF_test(model_RF4,testX,testY)

Model performance
Feature Importantce : 
[0.02621741 0.08807811 0.09189799 0.09668619 0.03990629 0.14748003
 0.14935428 0.11992112 0.08589193 0.03846456 0.02059316 0.057597
 0.03791192]
Total number of WNV occurence in test set : 196
Number of WNV occurence the model is able to capture in test set:181.0
Expected number of WNV occurence of models aussume prediction is normally distributed : 13670.897052778864
Log loss : 0.06785630091527631
This is to test the performance of random forest model, ideally, the logloss is low and also it is able to capture most of the WNV occurence, and also it is neither over predictingnor under predicting


In [105]:
data[['yr','templag2','templag3','templag4','precilag2','mirlag1','mirlag2','mirlag3','mirlag4', 'whitepct','owpct','dmipct','dhipct']].columns

Index(['yr', 'templag2', 'templag3', 'templag4', 'precilag2', 'mirlag1',
       'mirlag2', 'mirlag3', 'mirlag4', 'whitepct', 'owpct', 'dmipct',
       'dhipct'],
      dtype='object')

In [104]:
data.drop(columns=['wnvbinary','yrweeks','yrwksfid','yr_hexid','year']).columns[[17,20,9,10,16,18]]

Index(['mirlag3', 'whitepct', 'templag4', 'precilag1', 'mirlag2', 'mirlag4'], dtype='object')

In [96]:
data[data.drop(columns=['wnvbinary','yrweeks','yrwksfid','yr_hexid','year']).columns[[7,8,9,10,15,16,17,20]]].head() # From the above 3 feature importance of models, we can manually select 
# about 7 features which is mostly important

templag2  templag3  templag4  precilag1  mirlag1  mirlag2  mirlag3  \
0   13.7796   16.7306    9.0730   0.019091  0.00000  0.00000  0.00000   
1   15.9957   13.7796   16.7306   6.046130  0.00000  0.00000  0.00000   
2   16.9758   15.9957   13.7796  58.968242  2.50278  0.00000  0.00000   
3   25.3449   16.9758   15.9957  15.114200  0.00000  2.50278  0.00000   
4   21.0872   25.3449   16.9758   0.000000  0.00000  0.00000  2.50278   

   whitepct  
0  65.74257  
1  65.74257  
2  65.74257  
3  65.74257  
4  65.74257

In [97]:
x_selected = data[data.drop(columns=['wnvbinary','yrweeks','yrwksfid','yr_hexid','year']).columns[[7,8,9,10,15,16,17,20]]]
y_selected = y

### From the above model, we can see that random forest, although is not very good, can actually capture someinformation. So we will try formal Cross validation on selected features and see if it gets betterz

## Pipnelines for later for wrok

In [98]:
trainX_sel, testX_sel, trainY_sel, testY_sel = train_test_split(x_selected.values, y_selected, test_size = 0.2, shuffle = True) # CV

## Find best model 1

In [39]:
time_start = time.time()
params_RF_grid_1 = {
    'n_estimators' : [500, 1000],
    'max_features' : [90, 'sqrt', None],
    'max_depth' : [10, None],
    'min_samples_leaf' : [1,2]
}
CV_model_RF_1 = GridSearchCV(model_RF, params_RF_grid_1, scoring='neg_log_loss',cv=5)
CV_model_RF_1.fit(x_selected, dataY)
print("time consumed:", time.time() - time_start)

time consumed: 6569.04248213768


In [40]:
CV_model_RF_1.best_estimator_

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='sqrt', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=2, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=1000,
                      n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                      warm_start=False)

In [41]:
CV_model_RF_1.best_params_

{'max_depth': None,
 'max_features': 'sqrt',
 'min_samples_leaf': 2,
 'n_estimators': 1000}

In [18]:
time_start = time.time()
model_RF_best_1 = RandomForestClassifier(bootstrap= True, max_depth= 80, max_features= 'sqrt', min_samples_leaf= 5, min_samples_split= 8,n_estimators= 1000)
model_RF_best_1.fit(trainX,trainY)
print("Time consumed:", time.time() - time_start)

Time consumed: 31388.03477883339


In [19]:
model_RF_test(model_RF_best_1,testX,testY)

NameError: name 'model_RF_test' is not defined

## Find best model 2

In [ ]:
time_start = time.time()
params_RF_grid_2 = {
    'n_estimators' : [800, 1200],
    'max_features' : ['sqrt', 5],
    'min_samples_leaf' : [2,3]
}
CV_model_RF_2 = GridSearchCV(model_RF, params_RF_grid_2, cv=5)
CV_model_RF_2.fit(dataX, dataY)
print("time consumed:", time.time() - time_start)

In [24]:
CV_model_RF_2.fit(dataX, dataY)

KeyboardInterrupt: 

In [ ]:
CV_model_RF_2.best_params_

In [11]:
time_start = time.time()
model_RF_best_2 = RandomForestRegressor(n_estimators=1500,
                                 criterion="mse",
                                 n_jobs = -1,
                                 max_features=None,
                                 max_depth=None,
                                 bootstrap=True,
                                 min_samples_leaf=2
                                 )
model_RF_best_2.fit(trainX, trainY)
print("Time consumed:", time.time() - time_start)

Time consumed: 263.9204020500183


## Find best model 3

In [12]:
time_start = time.time()
param_grid = {
    'bootstrap': [True],
    'max_depth': [80, None, 110],
    'max_features': ['sqrt', 4],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [500, 2000, 4000, 1000]
}
CV_model_RF_3 = GridSearchCV(model_RF_best_2, params_RF_grid_3, cv=5)
CV_model_RF_3.fit(dataX, dataY)
print("time consumed:", time.time() - time_start)

time consumed: 998.9455091953278


In [13]:
CV_model_RF_3.best_estimator_

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='log2', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=2, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=3000,
                      n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                      warm_start=False)

In [14]:
CV_model_RF_3.best_params_

{'max_features': 'log2', 'min_samples_leaf': 2, 'n_estimators': 3000}

In [51]:
time_start = time.time()
model_RF_best_3 = RandomForestRegressor(n_estimators=8000,
                                 criterion="mse",
                                 n_jobs = -1,
                                 max_features="log2",
                                 max_depth=None,
                                 bootstrap=True,
                                 min_samples_leaf=2
                                 )
model_RF_best_3.fit(trainX, trainY)
print("Time consumed:", time.time() - time_start)

Time consumed: 45.644662857055664
