In [1]:
import imgaug as ia
ia.seed(1)
# imgaug uses matplotlib backend for displaying images
%matplotlib inline
from imgaug.augmentables.bbs import BoundingBox, BoundingBoxesOnImage
from imgaug import augmenters as iaa 
# imageio library will be used for image input/output
import imageio
import pandas as pd
import numpy as np
import re
import os
import glob

In [2]:
def convertYOLO2Other(image: np.array, yolo_label):
    # This function converts yolo bounding box to coordinates accpeted by imgaug library.
    H,W = image.shape[0], image.shape[1]
    yolo_bb = np.loadtxt(yolo_label)
    if yolo_bb.size== 0: return yolo_bb
    imgaug_bb = np.zeros(yolo_bb.shape)
    if yolo_bb.ndim <= 1: 
        class_id = yolo_bb[0]
        center_x, center_y, w, h = yolo_bb[1] * W, yolo_bb[2] * H, yolo_bb[3] * W, yolo_bb[4] * H
        x1 = center_x - w / 2
        y1 = center_y - h / 2
        x2 = center_x + w / 2
        y2 = center_y + h / 2
        imgaug_bb = np.array([class_id, x1, y1, x2, y2])
    else: 
        for n, bb in enumerate(yolo_bb):
            class_id = bb[0]
            center_x, center_y, w, h = bb[1] * W, bb[2] * H, bb[3] * W, bb[4] * H
            x1 = center_x - w / 2
            y1 = center_y - h / 2
            x2 = center_x + w / 2
            y2 = center_y + h / 2
            imgaug_bb[n] = np.array([class_id, x1, y1, x2, y2])
    print('This is YOLO label format:')
    print(yolo_bb)
    print('------------')
    print('This is imgaug label format:')
    print(imgaug_bb)
    print('------------')
    return imgaug_bb

In [3]:
# read all files in train folder
filenames = os.listdir('Train/')
img = []
lbl = []
for file in filenames: 
    if file.endswith('.jpg'):
        img.append(file)
    if file.endswith('.txt'):
        lbl.append(file)
img = np.asarray(img)
lbl = np.asarray(lbl)
N = img.shape[0]

In [4]:
# read images and labels into numpy array
# we assume all original input images have a constant dimension of 640 * 640 pixels
test = imageio.imread('Train/' + img[0])
H = test.shape[0]
W = test.shape[1]
channel = test.shape[2]
img_tensor_before_resize = np.zeros([N, H, W, channel], dtype='uint8')
bb_list_before_resize = []

In [5]:
for i, name in enumerate(img): 
    im = imageio.imread('Train/' + name)
    txt_file = name.split('.jpg')[0] + '.txt'
    img_tensor_before_resize[i] = im
    bb_list_before_resize.append(convertYOLO2Other(im, 'Train/' + txt_file))

Train/image-157_42.149727999999996_-87.884633.txt
This is YOLO label format:
[[1.       0.235156 0.848437 0.295312 0.28125 ]
 [1.       0.130469 0.5      0.235937 0.30625 ]
 [1.       0.661719 0.159375 0.332813 0.278125]
 [1.       0.85     0.453906 0.221875 0.285938]]
------------
This is imgaug label format:
[[  1.       56.      452.99968 244.99968 632.99968]
 [  1.        8.00032 222.      159.      418.     ]
 [  1.      317.       13.      530.00032 191.     ]
 [  1.      473.      198.99968 615.      382.     ]]
------------
Train/img-34_42.039688,-87.907642.txt
This is YOLO label format:
[[0.       0.209375 0.491406 0.19375  0.285938]
 [0.       0.410156 0.560937 0.164062 0.409375]
 [0.       0.740625 0.401562 0.1625   0.13125 ]]
------------
This is imgaug label format:
[[  0.       72.      222.99968 196.      406.     ]
 [  0.      210.      227.99968 314.99968 489.99968]
 [  0.      422.      214.99968 526.      298.99968]]
------------
Train/image-78_41.668475_-87.646016.t

<ipython-input-2-675e36e0feae>:4: UserWarning: loadtxt: Empty input file: "Train/img-60_42.039038,-87.898248.txt"
  yolo_bb = np.loadtxt(yolo_label)


Train/image-135_42.148427999999996_-87.878641.txt
This is YOLO label format:
[[1.       0.657813 0.482812 0.25625  0.20625 ]
 [1.       0.476562 0.889062 0.296875 0.221875]]
------------
This is imgaug label format:
[[  1.      339.00032 242.99968 503.00032 374.99968]
 [  1.      209.99968 497.99968 399.99968 639.99968]]
------------
Train/image-163_41.668475_-87.65457599999999.txt
This is YOLO label format:
[[0.       0.303125 0.633594 0.115625 0.142187]
 [0.       0.304688 0.808594 0.11875  0.145313]
 [0.       0.811719 0.61875  0.132812 0.153125]
 [0.       0.409375 0.185938 0.3875   0.128125]
 [0.       0.326562 0.953906 0.15625  0.092188]]
------------
This is imgaug label format:
[[  0.      157.      360.00032 231.      451.     ]
 [  0.      157.00032 471.      233.00032 564.00032]
 [  0.      477.00032 347.      562.      445.     ]
 [  0.      138.       78.00032 386.      160.00032]
 [  0.      158.99968 580.99968 258.99968 640.     ]]
------------
Train/image-277_42.1477779

<ipython-input-2-675e36e0feae>:4: UserWarning: loadtxt: Empty input file: "Train/img-2_42.040988,-87.90934999999999.txt"
  yolo_bb = np.loadtxt(yolo_label)


Train/img-63_42.038388,-87.908496.txt
This is YOLO label format:
[[0.       0.344531 0.113281 0.264062 0.182812]
 [0.       0.349219 0.301563 0.267188 0.128125]
 [0.       0.276562 0.539062 0.1375   0.2     ]
 [0.       0.357031 0.739062 0.282813 0.1375  ]
 [0.       0.728125 0.636719 0.1625   0.273438]
 [0.       0.9125   0.698438 0.165625 0.175   ]]
------------
This is imgaug label format:
[[  0.      136.       14.      304.99968 130.99968]
 [  0.      138.      152.00032 309.00032 234.00032]
 [  0.      132.99968 280.99968 220.99968 408.99968]
 [  0.      137.99968 428.99968 319.      516.99968]
 [  0.      414.      320.      518.      495.00032]
 [  0.      531.      391.00032 637.      503.00032]]
------------
Train/img-61_42.038388,-87.910204.txt
This is YOLO label format:
[[0.       0.121094 0.7875   0.170313 0.284375]
 [0.       0.285938 0.838281 0.115625 0.154688]
 [0.       0.507031 0.820312 0.164062 0.175   ]
 [0.       0.698438 0.825781 0.171875 0.160938]
 [0.       0.86

<ipython-input-2-675e36e0feae>:4: UserWarning: loadtxt: Empty input file: "Train/img-17_42.040338,-87.90934999999999.txt"
  yolo_bb = np.loadtxt(yolo_label)


Train/image-340_41.668475_-87.652864.txt
This is YOLO label format:
[[0.       0.550781 0.634375 0.151562 0.15    ]
 [0.       0.561719 0.807031 0.120313 0.154688]
 [0.       0.554688 0.952344 0.13125  0.095312]
 [0.       0.532813 0.128906 0.2125   0.114062]
 [0.       0.532031 0.023438 0.198437 0.04375 ]]
------------
This is imgaug label format:
[[  0.      304.      358.      400.99968 454.     ]
 [  0.      321.      466.99968 398.00032 566.     ]
 [  0.      313.00032 579.00032 397.00032 640.     ]
 [  0.      273.00032  46.      409.00032 118.99968]
 [  0.      277.        1.00032 403.99968  29.00032]]
------------
Train/img-25_42.040338,-87.90251799999999.txt
This is YOLO label format:
[[0.       0.067187 0.360938 0.13125  0.3375  ]
 [0.       0.302344 0.338281 0.157812 0.529687]
 [0.       0.504687 0.439063 0.15625  0.259375]
 [0.       0.71875  0.327344 0.184375 0.454688]
 [0.       0.910937 0.332031 0.178125 0.457813]]
------------
This is imgaug label format:
[[  0.        

<ipython-input-2-675e36e0feae>:4: UserWarning: loadtxt: Empty input file: "Train/img-58_42.039038,-87.89995599999999.txt"
  yolo_bb = np.loadtxt(yolo_label)


Train/image-124_41.667825_-87.659712.txt
This is YOLO label format:
[[1.       0.644531 0.182031 0.220312 0.110937]
 [1.       0.651563 0.330469 0.221875 0.123438]
 [1.       0.660156 0.48125  0.226562 0.109375]
 [1.       0.653125 0.629687 0.225    0.11875 ]
 [1.       0.6625   0.776563 0.23125  0.125   ]
 [1.       0.667188 0.930469 0.23125  0.120313]]
------------
This is imgaug label format:
[[  1.      342.       81.      482.99968 151.99968]
 [  1.      346.00032 172.      488.00032 251.00032]
 [  1.      350.      273.      494.99968 343.     ]
 [  1.      346.      364.99968 490.      440.99968]
 [  1.      350.      457.00032 498.      537.00032]
 [  1.      353.00032 557.      501.00032 634.00032]]
------------
Train/image-90_42.149077999999996_-87.892337.txt
This is YOLO label format:
[[1.       0.677344 0.490625 0.301563 0.278125]
 [1.       0.844531 0.201563 0.310937 0.309375]
 [1.       0.696875 0.857031 0.31875  0.276562]]
------------
This is imgaug label format:
[[  1.

In [8]:
aug = iaa.SomeOf(2, [    
    iaa.Affine(scale=(0.5, 1.5)),
    iaa.Affine(rotate=(-25, 25)),
    iaa.Affine(translate_percent={"x":(-0.3, 0.3),"y":(-0.3, 0.3)}),
    iaa.Fliplr(1),
    iaa.Multiply((0.5, 1.5)),
    iaa.GaussianBlur(sigma=(1.0, 3.0)),
    iaa.AdditiveGaussianNoise(scale=(0.03*255, 0.05*255))
])
resize = iaa.Resize(416)

In [75]:
# iterate over the training images to augment
N = img_tensor_before_resize.shape[0]
img_cell = []
bbox_cell = []
# file_name_cell = []
for n in range(N):
    flag = False
    # First, resize the n-th image from 640 * 640 to 416 to 416
    # image numpy array of shape (640,640,3)
    image_before_resize = img_tensor_before_resize[n]
    bbs_before_resize = 0
    assert image_before_resize.shape == (640, 640, 3)
    
    # numpy array of bounding boxes in format converted from YOLO beforehand
    bbs = bb_list_before_resize[n]
    
    
    if bbs.shape[0] == 0: 
        print('empty!')
        continue

    if bbs.ndim == 1: 
        print('only 1 bounding box!')
        print(bbs)
        flag = True
        
    # import bboxes before resizing into the imgaug data structures
    if flag:
        bbs_before_resize = BoundingBoxesOnImage.from_xyxy_array(bbs[1:].reshape(1, 4), shape=image_before_resize.shape)
    else:
        bbs_before_resize = BoundingBoxesOnImage.from_xyxy_array(bbs[:, 1:], shape=image_before_resize.shape)

    # set the label (0 or 1) for each bounding box
    for n, bb in enumerate(bbs_before_resize): 
        if flag:
            bb.label = bbs[0].astype('int')
        else:
            bb.label = bbs[n, 0].astype('int')
        
    flag = False
    
    # resize the image and its corresponding bbox coordinates
    resized_image, resized_bbs = resize(image=image_before_resize, bounding_boxes=bbs_before_resize)
    assert resized_image.shape == (416, 416, 3)
    W = 416
    H = 416
    # initialize empty lists to store the augmented images 
    # and bounding boxes respectively

    # give a batch size for how many augmented images can be obtained from one image.
    # Here, we want 5 augmented images generated from 1 original image
    batch_size = 5
    for i in range(batch_size): 
        # augment the resized images and resized bounding boxes randomly
        image_aug, bbs_aug = aug(image=resized_image, bounding_boxes=resized_bbs)
        #   disregard bounding boxes which have fallen out of image pane    
        bbs_aug = bbs_aug.remove_out_of_image()
        #   clip bounding boxes which are partially outside of image pane
        bbs_aug = bbs_aug.clip_out_of_image()
        img_cell.append(image_aug)
        bbox_cell.append(bbs_aug)
#         old_name = img[n].split('.jpg')[0]
#         old_name = img[n]
#         new_name = '%s_aug_%d'%(old_name, i)
#         file_name_cell.append(new_name)


empty!
only 1 bounding box!
[  1.      137.00032 293.00032 334.      497.00032]
only 1 bounding box!
[  1.      308.99968 410.99968 528.99968 626.99968]
only 1 bounding box!
[  0.       67.       79.      216.00032 229.     ]
only 1 bounding box!
[  1.      240.00032 365.00032 430.00032 470.     ]
only 1 bounding box!
[  0.      376.00032  92.      538.00032 167.00032]
only 1 bounding box!
[  1.       93.      255.00032 266.00032 467.00032]
only 1 bounding box!
[  1.      279.99968 140.      637.99968 300.     ]
empty!
only 1 bounding box!
[  1.      402.00032  76.      600.00032 391.00032]
only 1 bounding box!
[  0.      301.99968 546.99968 547.99968 638.99968]
only 1 bounding box!
[  1.      240.99968 126.99968 356.      302.     ]
only 1 bounding box!
[  1.      371.00032 358.00032 640.      489.     ]
only 1 bounding box!
[  0.      264.99968 147.      400.99968 276.00032]
only 1 bounding box!
[  0.       25.00032 201.      106.      374.00032]
empty!
only 1 bounding box!
[  1.   4

In [74]:
print(len(img_cell))
print(len(bbox_cell))

2145
2145


In [76]:
for i, img in enumerate(img_cell):
#     new_name = file_name_cell[i]
#     print(new_name)
    new_name = 'aug_image_' + str(i)
    imageio.imwrite('Augmented/' + new_name + '.jpg', img)
    bb_on_image = bbox_cell[i]
    out_file = open('Augmented/' + new_name + '.txt', 'w')
    for bb in bb_on_image:
        classIndex = bb.label
        w = bb.width / W
        h = bb.height / H
        xcen = bb.center_x / W
        ycen = bb.center_y / H
        # print (classIndex, xcen, ycen, w, h)
        # https://github.com/tzutalin/labelImg/blob/master/libs/yolo_io.py
        out_file.write("%d %.6f %.6f %.6f %.6f\n" % (classIndex, xcen, ycen, w, h))
    out_file.close()